In [1]:
model="model(1)"

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

Mounted at /content/drive


In [14]:
import shutil
import os

# Source and destination folder paths
source_folder = '/content/drive/MyDrive/Kaggle/TestNoteBook'
destination_folder = '/content'

# Get a list of all files in the source folder
files = os.listdir(source_folder)

# Copy each file to the destination folder
for file in files:
    source_file_path = os.path.join(source_folder, file)
    destination_file_path = os.path.join(destination_folder, file)
    shutil.copy2(source_file_path, destination_file_path)



# Source and destination folder paths
source_folder = f"/content/drive/MyDrive/Kaggle/{model}"
destination_folder = '/content'

# Get a list of all files in the source folder
files = os.listdir(source_folder)

# Copy each file to the destination folder
for file in files:
    source_file_path = os.path.join(source_folder, file)
    destination_file_path = os.path.join(destination_folder, file)
    shutil.copy2(source_file_path, destination_file_path)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


##Preprocessing Test Data

In [10]:
%run cleaning_test.py --model {model}

Loaded Vocab 41 {'ؤ': 0, 'د': 1, 'س': 2, 'آ': 3, 'ذ': 4, 'ت': 5, 'ح': 6, 'ل': 7, 'أ': 8, 'غ': 9, 'م': 10, 'ض': 11, 'ك': 12, 'ز': 13, 'ظ': 14, 'ق': 15, 'ص': 16, 'ه': 17, 'ا': 18, 'ش': 19, 'ع': 20, 'و': 21, 'ئ': 22, 'ى': 23, 'إ': 24, 'خ': 25, 'ط': 26, 'ء': 27, 'ر': 28, 'ي': 29, 'ف': 30, 'ث': 31, 'ن': 32, 'ب': 33, 'ج': 34, 'ة': 35, '<s>': 36, '</s>': 37, ' ': 38, '<PAD>': 39, '<UNK>': 40}
Model model(1)
ليس للوكيل
Cleaning .....
all_punctuation {'\\', '$', '>', '_', '(', ']', '%', '~', ',', '.', '?', '`', '|', '!', '#', '"', "'", ')', '=', '}', '-', '^', '&', '[', '@', ';', '{', ':', '+', '*', '/', '<'}
Done Cleaning :D
Tokenization to Sentences [
.,،؛:«»?؟]+ .....
Done Tokenizing :D
Removing Tashkel ......
Preparing X Done :D 9136 Sentences
['ل', 'ي', 'س', ' ', 'ل', 'ل', 'و', 'ك', 'ي', 'ل', ' ', 'ب', 'ا', 'ل', 'ق', 'ب', 'ض', ' ', 'أ', 'ن', ' ', 'ي', 'ب', 'ر', 'أ', ' ', 'ا', 'ل', 'م', 'د', 'ي', 'ن', ' ', 'أ', 'و', ' ', 'ي', 'ه', 'ب', ' ', 'ا', 'ل', 'د', 'ي', 'ن', ' ', 'ل', 'ه', ' ', 'أ', 

#Test DataLoader

In [15]:
from utils import get_params
from Globals import vocab_map,classes
from tashkeel_data_set_test import TashkeelDatasetTest

v_sentences, _, v_size = get_params(vocab_map, classes, f'/content/drive/MyDrive/Kaggle/{model}/X.pickle', '',test=True)
max_length=300
val_dataset_test = TashkeelDatasetTest(v_sentences, vocab_map['<PAD>'],max_length)

{'ؤ': 0, 'د': 1, 'س': 2, 'آ': 3, 'ذ': 4, 'ت': 5, 'ح': 6, 'ل': 7, 'أ': 8, 'غ': 9, 'م': 10, 'ض': 11, 'ك': 12, 'ز': 13, 'ظ': 14, 'ق': 15, 'ص': 16, 'ه': 17, 'ا': 18, 'ش': 19, 'ع': 20, 'و': 21, 'ئ': 22, 'ى': 23, 'إ': 24, 'خ': 25, 'ط': 26, 'ء': 27, 'ر': 28, 'ي': 29, 'ف': 30, 'ث': 31, 'ن': 32, 'ب': 33, 'ج': 34, 'ة': 35, '<s>': 36, '</s>': 37, ' ': 38, '<PAD>': 39, '<UNK>': 40}
{'َ': 0, 'ً': 1, 'ُ': 2, 'ٌ': 3, 'ِ': 4, 'ٍ': 5, 'ْ': 6, 'ّ': 7, 'َّ': 8, 'ًّ': 9, 'ُّ': 10, 'ٌّ': 11, 'ِّ': 12, 'ٍّ': 13, '': 14, 'P': 15}
Padding ..... with  300 : 9136
Done Padding ..... 9336


#Loading Model

In [16]:
from tashkeel_nn import Tashkeel
from utils import *
model_loaded = Tashkeel()
model_loaded.load_state_dict(torch.load(f'/content/drive/MyDrive/Kaggle/{model}/model.pth'))
model_loaded.eval()
print(model_loaded)

for param in model_loaded.parameters():
  print(param.data)

Tashkeel(
  (embedding): Embedding(41, 100)
  (lstm): LSTM(100, 128, num_layers=2, batch_first=True, bidirectional=True)
  (linear): Linear(in_features=256, out_features=16, bias=True)
)
tensor([[-1.5912, -1.7107, -0.9594,  ..., -1.0248, -0.7629,  0.2807],
        [ 0.0446,  0.6646,  0.9100,  ...,  0.6760, -0.6986,  0.8877],
        [ 0.2853,  0.3606, -1.2643,  ..., -1.2524, -0.5790,  0.1902],
        ...,
        [ 0.8400, -0.1165,  0.1098,  ...,  0.4060, -1.0944,  0.1252],
        [-0.7768,  1.7390,  0.1961,  ..., -1.3798, -2.4022, -0.2137],
        [ 0.5404, -0.2689,  0.1586,  ..., -0.1648, -0.6653,  0.1134]])
tensor([[-0.3640, -0.0709, -0.2280,  ..., -0.4350, -0.0640, -0.2402],
        [ 0.1095, -0.0325, -0.0273,  ..., -0.0288, -0.3282, -0.2246],
        [ 0.3512, -0.3106, -0.1818,  ..., -0.1542, -0.0916,  0.0738],
        ...,
        [-0.0255,  0.0339, -0.0110,  ..., -0.0198,  0.2555,  0.2859],
        [ 0.0378,  0.2411, -0.1196,  ..., -0.0595,  0.0702, -0.1586],
        [-0.0725

In [17]:
from tashkeel_result import result
result(model_loaded, val_dataset_test, batch_size=512)

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([2, 6, 0,  ..., 0, 0, 3], device='cuda:0')


  5%|▌         | 1/19 [00:01<00:31,  1.78s/it]

tensor([ 0, 12,  0,  ...,  0, 14, 14], device='cuda:0')


 11%|█         | 2/19 [00:02<00:19,  1.13s/it]

tensor([0, 0, 0,  ..., 0, 0, 5], device='cuda:0')


 16%|█▌        | 3/19 [00:03<00:14,  1.09it/s]

tensor([ 0,  0,  6,  ...,  4, 14,  3], device='cuda:0')


 21%|██        | 4/19 [00:03<00:12,  1.22it/s]

tensor([ 0,  6,  2,  ..., 14,  0,  2], device='cuda:0')


 26%|██▋       | 5/19 [00:04<00:11,  1.26it/s]

tensor([14,  2,  4,  ...,  6,  6,  3], device='cuda:0')


 32%|███▏      | 6/19 [00:05<00:11,  1.10it/s]

tensor([0, 2, 0,  ..., 6, 2, 0], device='cuda:0')


 37%|███▋      | 7/19 [00:06<00:11,  1.08it/s]

tensor([14,  6,  0,  ...,  4, 14,  2], device='cuda:0')


 42%|████▏     | 8/19 [00:07<00:10,  1.05it/s]

tensor([14,  0,  6,  ...,  4,  0,  3], device='cuda:0')


 47%|████▋     | 9/19 [00:08<00:09,  1.03it/s]

tensor([ 2,  4, 10,  ...,  0,  0,  2], device='cuda:0')


 53%|█████▎    | 10/19 [00:09<00:08,  1.04it/s]

tensor([0, 4, 0,  ..., 0, 0, 5], device='cuda:0')


 58%|█████▊    | 11/19 [00:10<00:07,  1.13it/s]

tensor([0, 6, 0,  ..., 6, 0, 5], device='cuda:0')


 63%|██████▎   | 12/19 [00:11<00:06,  1.13it/s]

tensor([0, 8, 3,  ..., 6, 0, 5], device='cuda:0')


 68%|██████▊   | 13/19 [00:11<00:04,  1.21it/s]

tensor([ 0,  6,  0,  ...,  4, 14,  3], device='cuda:0')


 74%|███████▎  | 14/19 [00:12<00:03,  1.28it/s]

tensor([0, 0, 0,  ..., 0, 6, 2], device='cuda:0')


 79%|███████▉  | 15/19 [00:13<00:02,  1.34it/s]

tensor([ 2,  3,  0,  ...,  0, 12,  0], device='cuda:0')


 84%|████████▍ | 16/19 [00:13<00:02,  1.41it/s]

tensor([0, 4, 0,  ..., 6, 6, 0], device='cuda:0')


 89%|████████▉ | 17/19 [00:14<00:01,  1.34it/s]

tensor([ 4, 14,  0,  ...,  6,  4,  5], device='cuda:0')


100%|██████████| 19/19 [00:15<00:00,  1.22it/s]


tensor([0, 6, 0,  ..., 0, 4, 2], device='cuda:0')
            ID  label
0            0      2
1            1      6
2            2      0
3            3      0
4            4      6
...        ...    ...
417354  417354      0
417355  417355      6
417356  417356      0
417357  417357      4
417358  417358      2

[417359 rows x 2 columns]


In [20]:
from google.colab import files
files.download('csv_dictionary.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>