#Model(1)

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:

model="model(1)"
import shutil
import os

# Source and destination folder paths
source_folder = '/content/drive/MyDrive/Kaggle/TestNoteBook'
destination_folder = '/content'

# Get a list of all files in the source folder
files = os.listdir(source_folder)

# Copy each file to the destination folder
for file in files:
    source_file_path = os.path.join(source_folder, file)
    destination_file_path = os.path.join(destination_folder, file)
    shutil.copy2(source_file_path, destination_file_path)



# Source and destination folder paths
source_folder = f"/content/drive/MyDrive/Kaggle/{model}"
destination_folder = '/content'

# Get a list of all files in the source folder
files = os.listdir(source_folder)

# Copy each file to the destination folder
for file in files:
    source_file_path = os.path.join(source_folder, file)
    destination_file_path = os.path.join(destination_folder, file)
    shutil.copy2(source_file_path, destination_file_path)

In [19]:
def merge_text_files(file1, file2, output_file):
    # with open(file1, 'r') as f1, open(file2, 'r') as f2, open(file3, 'r') as f3:
    with open(file1, 'r') as f1, open(file2, 'r') as f2:
        content1 = f1.read()
        content2 = f2.read()

    with open(output_file, 'w') as output:
        output.write(content1)
        output.write('\n')  # Add a newline between files if needed
        output.write(content2)

# Replace 'file1.txt', 'file2.txt', 'file3.txt', and 'output.txt' with your file names
merge_text_files('/content/drive/MyDrive/Tashkeel/val.txt', '/content/drive/MyDrive/Tashkeel/train.txt', '/content/drive/MyDrive/Tashkeel/val_train.txt')


In [24]:
# %run cleaning.py --mode valtrain

In [ ]:
# %run cleaning.py --mode train

In [6]:
# %run cleaning.py --mode all

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


Loaded Vocab 41 {'ت': 0, 'ه': 1, 'س': 2, 'ئ': 3, 'ي': 4, 'خ': 5, 'ب': 6, 'ش': 7, 'ح': 8, 'ى': 9, 'ن': 10, 'إ': 11, 'ل': 12, 'ؤ': 13, 'ط': 14, 'ج': 15, 'ف': 16, 'آ': 17, 'ص': 18, 'م': 19, 'ا': 20, 'ع': 21, 'و': 22, 'غ': 23, 'ك': 24, 'ظ': 25, 'د': 26, 'ر': 27, 'ق': 28, 'أ': 29, 'ذ': 30, 'ة': 31, 'ء': 32, 'ز': 33, 'ض': 34, 'ث': 35, '<s>': 36, '</s>': 37, ' ': 38, '<PAD>': 39, '<UNK>': 40}
All mode selected.
Cleaning .....
all_punctuation {'#', '_', '>', '@', ')', '}', '*', '(', '|', '$', '&', '+', ']', '=', '`', '^', '[', '.', '<', '~', '%', ',', "'", ':', '\\', '{', '!', '/', ';', '"', '-', '?'}
Done Cleaning :D
Tokenization to Sentences [
.,،؛:«»?؟]+ .....
Done Tokenizing :D
Fxing Diacritization issues .......
Done Fxing Diacritization issues :D
Removing Tashkel ......
Removing Tashkel Done :D 398012 Sentences
Getting Tashkel ......
Getting Tashkeel Done :D 398012 Sentences
['ا', 'ل', 'ش', 'ه', 'ا', 'د', 'ة', ' ', 'ظ', 'ا', 'ه', 'ر', 'ة']
[14, 14, 8, 0, 14, 0, 4, 14, 0, 14, 4, 0, 1]


In [ ]:
# %run cleaning.py --mode combine

combine mode selected.
Cleaning .....
all_punctuation {"'", '}', '_', '~', '<', ';', '!', '.', '>', '\\', '[', '+', '=', '"', ':', '%', '?', '^', '`', '$', ']', '(', '@', '-', '|', '#', '/', '{', ',', '&', ')', '*'}
Done Cleaning :D
Tokenization to Sentences [
.,،؛:«»?؟]+ .....
Done Tokenizing :D
Fxing Diacritization issues .......
Done Fxing Diacritization issues :D
Removing Tashkel ......
Removing Tashkel Done :D 203938 Sentences
Getting Tashkel ......
Getting Tashkeel Done :D 203938 Sentences
['ق', 'و', 'ل', 'ه']
[0, 6, 2, 2]


In [ ]:
# %run cleaning.py --mode validate

Validation mode selected.
Cleaning .....
all_punctuation {"'", '}', '_', '~', '<', ';', '!', '.', '>', '\\', '[', '+', '=', '"', ':', '%', '?', '^', '`', '$', ']', '(', '@', '-', '|', '#', '/', '{', ',', '&', ')', '*'}
Done Cleaning :D
Tokenization to Sentences [
.,،؛:«»?؟]+ .....
Done Tokenizing :D
Fxing Diacritization issues .......
Done Fxing Diacritization issues :D
Removing Tashkel ......
Removing Tashkel Done :D 9399 Sentences
Getting Tashkel ......
Getting Tashkeel Done :D 9399 Sentences
['ق', 'و', 'ل', 'ه']
[0, 6, 2, 2]


In [ ]:
# %run cleaning.py --mode test

Testing mode selected.
Cleaning .....
all_punctuation {"'", '}', '_', '~', '<', ';', '!', '.', '>', '\\', '[', '+', '=', '"', ':', '%', '?', '^', '`', '$', ']', '(', '@', '-', '|', '#', '/', '{', ',', '&', ')', '*'}
Done Cleaning :D
Tokenization to Sentences [
.,،؛:«»?؟]+ .....
Done Tokenizing :D
Fxing Diacritization issues .......
Done Fxing Diacritization issues :D
Removing Tashkel ......
Removing Tashkel Done :D 9500 Sentences
Getting Tashkel ......
Getting Tashkeel Done :D 9500 Sentences
['ق', 'و', 'ل', 'ه']
[0, 6, 2, 2]


In [7]:
from utils import get_params
from Globals import vocab_map,classes

# t_sentences, t_labels, t_size = get_params(vocab_map, classes, '/content/drive/MyDrive/Tashkeel/train_X.pickle', '/content/drive/MyDrive/Tashkeel/train_Y.pickle')
# v_sentences, v_labels, v_size = get_params(vocab_map, classes, '/content/drive/MyDrive/Tashkeel/val_X.pickle', '/content/drive/MyDrive/Tashkeel/val_Y.pickle')
# test_sentences, test_labels, test_size = get_params(vocab_map, classes, '/content/drive/MyDrive/Tashkeel/test_X.pickle', '/content/drive/MyDrive/Tashkeel/test_Y.pickle')
# c_sentences, c_labels, c_size = get_params(vocab_map, classes, '/content/drive/MyDrive/Tashkeel/combine_X.pickle', '/content/drive/MyDrive/Tashkeel/combine_Y.pickle')
# a_sentences, a_labels, a_size = get_params(vocab_map, classes, '/content/drive/MyDrive/Tashkeel/all_X.pickle', '/content/drive/MyDrive/Tashkeel/all_Y.pickle')
val_train_sentences, val_train_labels, val_train_size = get_params(vocab_map, classes, '/content/drive/MyDrive/Tashkeel/val_train_X.pickle', '/content/drive/MyDrive/Tashkeel/val_train_Y.pickle')

from tashkeel_data_set import TashkeelDataset
max_length=300
# train_dataset = TashkeelDataset(t_sentences, t_labels, vocab_map['<PAD>'],max_length)
# val_dataset = TashkeelDataset(v_sentences, v_labels, vocab_map['<PAD>'],max_length)
# test_dataset = TashkeelDataset(test_sentences, test_labels, vocab_map['<PAD>'],max_length)
# combine_dataset = TashkeelDataset(c_sentences, c_labels, vocab_map['<PAD>'],max_length)
# all_dataset = TashkeelDataset(a_sentences, a_labels, vocab_map['<PAD>'],max_length)
val_train_dataset = TashkeelDataset(val_train_sentences, val_train_labels, vocab_map['<PAD>'],max_length)


{'ت': 0, 'ه': 1, 'س': 2, 'ئ': 3, 'ي': 4, 'خ': 5, 'ب': 6, 'ش': 7, 'ح': 8, 'ى': 9, 'ن': 10, 'إ': 11, 'ل': 12, 'ؤ': 13, 'ط': 14, 'ج': 15, 'ف': 16, 'آ': 17, 'ص': 18, 'م': 19, 'ا': 20, 'ع': 21, 'و': 22, 'غ': 23, 'ك': 24, 'ظ': 25, 'د': 26, 'ر': 27, 'ق': 28, 'أ': 29, 'ذ': 30, 'ة': 31, 'ء': 32, 'ز': 33, 'ض': 34, 'ث': 35, '<s>': 36, '</s>': 37, ' ': 38, '<PAD>': 39, '<UNK>': 40}
{'َ': 0, 'ً': 1, 'ُ': 2, 'ٌ': 3, 'ِ': 4, 'ٍ': 5, 'ْ': 6, 'ّ': 7, 'َّ': 8, 'ًّ': 9, 'ُّ': 10, 'ٌّ': 11, 'ِّ': 12, 'ٍّ': 13, '': 14, 'P': 15}
UNK –
UNK ‏
UNK –
UNK –
UNK ‏
UNK –
UNK –
UNK ‏
UNK –
UNK ‏
UNK –
UNK –
Padding ..... with  300 : 398012 398012
Done Padding ..... 406592 406592


In [13]:
from tashkeel_nn import Tashkeel
model = Tashkeel()
print(model)

Tashkeel(
  (embedding): Embedding(41, 100)
  (lstm): LSTM(100, 256, num_layers=2, batch_first=True, bidirectional=True)
  (linear): Linear(in_features=512, out_features=16, bias=True)
)


In [18]:
from tashkeel_train import train
train(model, val_train_dataset)

Loaded Vocab 41 {'ت': 0, 'ه': 1, 'س': 2, 'ئ': 3, 'ي': 4, 'خ': 5, 'ب': 6, 'ش': 7, 'ح': 8, 'ى': 9, 'ن': 10, 'إ': 11, 'ل': 12, 'ؤ': 13, 'ط': 14, 'ج': 15, 'ف': 16, 'آ': 17, 'ص': 18, 'م': 19, 'ا': 20, 'ع': 21, 'و': 22, 'غ': 23, 'ك': 24, 'ظ': 25, 'د': 26, 'ر': 27, 'ق': 28, 'أ': 29, 'ذ': 30, 'ة': 31, 'ء': 32, 'ز': 33, 'ض': 34, 'ث': 35, '<s>': 36, '</s>': 37, ' ': 38, '<PAD>': 39, '<UNK>': 40}
Using GPU


  0%|          | 0/795 [00:00<?, ?it/s]

Epoch: 0/5............. 

  0%|          | 1/795 [00:00<10:04,  1.31it/s]

Loss: 0.0236
acc: 0.9922845655087478
Epoch: 0/5............. 

  0%|          | 2/795 [00:01<09:49,  1.35it/s]

Loss: 0.0328
acc: 0.9894539150534527
Epoch: 0/5............. 

  0%|          | 3/795 [00:02<09:38,  1.37it/s]

Loss: 0.0255
acc: 0.9908913467794405
Epoch: 0/5............. 

  1%|          | 4/795 [00:02<09:35,  1.37it/s]

Loss: 0.0299
acc: 0.9903552595059673
Epoch: 0/5............. 

  1%|          | 5/795 [00:03<09:34,  1.37it/s]

Loss: 0.0269
acc: 0.9912467819051122
Epoch: 0/5............. 

  1%|          | 6/795 [00:04<09:33,  1.38it/s]

Loss: 0.0318
acc: 0.9901439720129172
Epoch: 0/5............. 

  1%|          | 7/795 [00:05<09:34,  1.37it/s]

Loss: 0.0277
acc: 0.9907565253627306
Epoch: 0/5............. 

  1%|          | 8/795 [00:05<09:31,  1.38it/s]

Loss: 0.0315
acc: 0.9901441548875872
Epoch: 0/5............. 

  1%|          | 9/795 [00:06<09:33,  1.37it/s]

Loss: 0.0289
acc: 0.9909131205673759
Epoch: 0/5............. 

  1%|▏         | 10/795 [00:07<09:31,  1.37it/s]

Loss: 0.0296
acc: 0.990869284817216
Epoch: 0/5............. 

  1%|▏         | 11/795 [00:08<09:32,  1.37it/s]

Loss: 0.0294
acc: 0.9904034601608435
Epoch: 0/5............. 

  2%|▏         | 12/795 [00:08<09:35,  1.36it/s]

Loss: 0.0345
acc: 0.9890816114988598
Epoch: 0/5............. 

  2%|▏         | 13/795 [00:09<09:34,  1.36it/s]

Loss: 0.0339
acc: 0.9895497107794573
Epoch: 0/5............. 

  2%|▏         | 14/795 [00:10<09:34,  1.36it/s]

Loss: 0.0257
acc: 0.9916877484640405
Epoch: 0/5............. 

  2%|▏         | 15/795 [00:10<09:35,  1.35it/s]

Loss: 0.0253
acc: 0.9913107001422584
Epoch: 0/5............. 

  2%|▏         | 16/795 [00:11<09:36,  1.35it/s]

Loss: 0.0306
acc: 0.9904905068461815
Epoch: 0/5............. 

  2%|▏         | 17/795 [00:12<09:34,  1.35it/s]

Loss: 0.0264
acc: 0.9918474139238587
Epoch: 0/5............. 

  2%|▏         | 18/795 [00:13<09:36,  1.35it/s]

Loss: 0.0292
acc: 0.9907812612095559
Epoch: 0/5............. 

  2%|▏         | 19/795 [00:13<09:36,  1.35it/s]

Loss: 0.0321
acc: 0.9896214466647903
Epoch: 0/5............. 

  3%|▎         | 20/795 [00:14<09:34,  1.35it/s]

Loss: 0.0302
acc: 0.9899130204716077
Epoch: 0/5............. 

  3%|▎         | 21/795 [00:15<09:33,  1.35it/s]

Loss: 0.0294
acc: 0.9910055350553506
Epoch: 0/5............. 

  3%|▎         | 22/795 [00:16<09:37,  1.34it/s]

Loss: 0.0308
acc: 0.9898545606318425
Epoch: 0/5............. 

  3%|▎         | 23/795 [00:16<09:36,  1.34it/s]

Loss: 0.0291
acc: 0.9905932386650328
Epoch: 0/5............. 

  3%|▎         | 24/795 [00:17<09:38,  1.33it/s]

Loss: 0.0308
acc: 0.9900258117969472
Epoch: 0/5............. 

  3%|▎         | 25/795 [00:18<09:35,  1.34it/s]

Loss: 0.0253
acc: 0.9913171926790604
Epoch: 0/5............. 

  3%|▎         | 26/795 [00:19<09:38,  1.33it/s]

Loss: 0.0350
acc: 0.9890618287564853
Epoch: 0/5............. 

  3%|▎         | 27/795 [00:19<09:39,  1.33it/s]

Loss: 0.0287
acc: 0.9904612196777536
Epoch: 0/5............. 

  4%|▎         | 28/795 [00:20<09:38,  1.33it/s]

Loss: 0.0306
acc: 0.9897430823521651
Epoch: 0/5............. 

  4%|▎         | 29/795 [00:21<09:40,  1.32it/s]

Loss: 0.0294
acc: 0.9905306832630664
Epoch: 0/5............. 

  4%|▍         | 30/795 [00:22<09:39,  1.32it/s]

Loss: 0.0272
acc: 0.9910579171825561
Epoch: 0/5............. 

  4%|▍         | 31/795 [00:23<09:42,  1.31it/s]

Loss: 0.0265
acc: 0.9916723372541395
Epoch: 0/5............. 

  4%|▍         | 32/795 [00:23<09:45,  1.30it/s]

Loss: 0.0275
acc: 0.9910477557004274
Epoch: 0/5............. 

  4%|▍         | 33/795 [00:24<09:42,  1.31it/s]

Loss: 0.0297
acc: 0.9900872323552736
Epoch: 0/5............. 

  4%|▍         | 34/795 [00:25<09:43,  1.30it/s]

Loss: 0.0268
acc: 0.9908074264413159
Epoch: 0/5............. 

  4%|▍         | 35/795 [00:26<09:45,  1.30it/s]

Loss: 0.0284
acc: 0.9904900425151041
Epoch: 0/5............. 

  5%|▍         | 36/795 [00:26<09:44,  1.30it/s]

Loss: 0.0315
acc: 0.9898220458327999
Epoch: 0/5............. 

  5%|▍         | 37/795 [00:27<09:45,  1.29it/s]

Loss: 0.0320
acc: 0.9897407879560493
Epoch: 0/5............. 

  5%|▍         | 38/795 [00:28<09:48,  1.29it/s]

Loss: 0.0314
acc: 0.9894332957763635
Epoch: 0/5............. 

  5%|▍         | 39/795 [00:29<09:48,  1.28it/s]

Loss: 0.0272
acc: 0.9914140711902113
Epoch: 0/5............. 

  5%|▌         | 40/795 [00:30<09:49,  1.28it/s]

Loss: 0.0307
acc: 0.9896693421406352
Epoch: 0/5............. 

  5%|▌         | 41/795 [00:30<09:49,  1.28it/s]

Loss: 0.0287
acc: 0.9912107081753833
Epoch: 0/5............. 

  5%|▌         | 42/795 [00:31<09:51,  1.27it/s]

Loss: 0.0282
acc: 0.9906803984467331
Epoch: 0/5............. 

  5%|▌         | 43/795 [00:32<09:51,  1.27it/s]

Loss: 0.0309
acc: 0.9895326416307042
Epoch: 0/5............. 

  6%|▌         | 44/795 [00:33<09:48,  1.28it/s]

Loss: 0.0272
acc: 0.9911174344382065
Epoch: 0/5............. 

  6%|▌         | 45/795 [00:33<09:49,  1.27it/s]

Loss: 0.0261
acc: 0.9918502202643171
Epoch: 0/5............. 

  6%|▌         | 46/795 [00:34<09:49,  1.27it/s]

Loss: 0.0276
acc: 0.9914672088223516
Epoch: 0/5............. 

  6%|▌         | 47/795 [00:35<09:50,  1.27it/s]

Loss: 0.0317
acc: 0.9884829505915101
Epoch: 0/5............. 

  6%|▌         | 48/795 [00:36<09:47,  1.27it/s]

Loss: 0.0337
acc: 0.9879911804079061
Epoch: 0/5............. 

  6%|▌         | 49/795 [00:37<09:48,  1.27it/s]

Loss: 0.0238
acc: 0.9927286643704554
Epoch: 0/5............. 

  6%|▋         | 50/795 [00:37<09:49,  1.26it/s]

Loss: 0.0284
acc: 0.9906161797588064
Epoch: 0/5............. 

  6%|▋         | 51/795 [00:38<09:48,  1.26it/s]

Loss: 0.0252
acc: 0.9914562174032391
Epoch: 0/5............. 

  7%|▋         | 52/795 [00:39<09:45,  1.27it/s]

Loss: 0.0297
acc: 0.9907309231453295
Epoch: 0/5............. 

  7%|▋         | 53/795 [00:40<09:45,  1.27it/s]

Loss: 0.0333
acc: 0.9890560875512996
Epoch: 0/5............. 

  7%|▋         | 54/795 [00:41<09:43,  1.27it/s]

Loss: 0.0314
acc: 0.9897863190431394
Epoch: 0/5............. 

  7%|▋         | 55/795 [00:41<09:40,  1.28it/s]

Loss: 0.0242
acc: 0.9921216961951786
Epoch: 0/5............. 

  7%|▋         | 56/795 [00:42<09:40,  1.27it/s]

Loss: 0.0328
acc: 0.9894608695652174
Epoch: 0/5............. 

  7%|▋         | 57/795 [00:43<09:38,  1.28it/s]

Loss: 0.0338
acc: 0.9885768985322272
Epoch: 0/5............. 

  7%|▋         | 58/795 [00:44<09:37,  1.28it/s]

Loss: 0.0309
acc: 0.9901068054224291
Epoch: 0/5............. 

  7%|▋         | 59/795 [00:44<09:34,  1.28it/s]

Loss: 0.0312
acc: 0.9901309231075962
Epoch: 0/5............. 

  8%|▊         | 60/795 [00:45<09:30,  1.29it/s]

Loss: 0.0311
acc: 0.9904837145832586
Epoch: 0/5............. 

  8%|▊         | 61/795 [00:46<09:31,  1.28it/s]

Loss: 0.0286
acc: 0.9903955876759224
Epoch: 0/5............. 

  8%|▊         | 62/795 [00:47<09:29,  1.29it/s]

Loss: 0.0310
acc: 0.9892342420559125
Epoch: 0/5............. 

  8%|▊         | 63/795 [00:48<09:26,  1.29it/s]

Loss: 0.0280
acc: 0.9906833361877033
Epoch: 0/5............. 

  8%|▊         | 64/795 [00:48<09:24,  1.29it/s]

Loss: 0.0330
acc: 0.9892250456268427
Epoch: 0/5............. 

  8%|▊         | 65/795 [00:49<09:22,  1.30it/s]

Loss: 0.0316
acc: 0.9897026967632562
Epoch: 0/5............. 

  8%|▊         | 66/795 [00:50<09:19,  1.30it/s]

Loss: 0.0288
acc: 0.9900628212450029
Epoch: 0/5............. 

  8%|▊         | 67/795 [00:51<09:19,  1.30it/s]

Loss: 0.0225
acc: 0.9928613304824637
Epoch: 0/5............. 

  9%|▊         | 68/795 [00:51<09:16,  1.31it/s]

Loss: 0.0238
acc: 0.9922948317220324
Epoch: 0/5............. 

  9%|▊         | 69/795 [00:52<09:14,  1.31it/s]

Loss: 0.0248
acc: 0.9917446535957015
Epoch: 0/5............. 

  9%|▉         | 70/795 [00:53<09:12,  1.31it/s]

Loss: 0.0283
acc: 0.9905971563981043
Epoch: 0/5............. 

  9%|▉         | 71/795 [00:54<09:11,  1.31it/s]

Loss: 0.0370
acc: 0.9898420248004077
Epoch: 0/5............. 

  9%|▉         | 72/795 [00:54<09:11,  1.31it/s]

Loss: 0.0247
acc: 0.9923175849465277
Epoch: 0/5............. 

  9%|▉         | 73/795 [00:55<09:07,  1.32it/s]

Loss: 0.0271
acc: 0.9914146929246527
Epoch: 0/5............. 

  9%|▉         | 74/795 [00:56<09:05,  1.32it/s]

Loss: 0.0298
acc: 0.9906055073786704
Epoch: 0/5............. 

  9%|▉         | 75/795 [00:57<09:05,  1.32it/s]

Loss: 0.0292
acc: 0.9910745593063658
Epoch: 0/5............. 

 10%|▉         | 76/795 [00:57<09:03,  1.32it/s]

Loss: 0.0269
acc: 0.9911741862599732
Epoch: 0/5............. 

 10%|▉         | 77/795 [00:58<09:03,  1.32it/s]

Loss: 0.0299
acc: 0.9895520349631248
Epoch: 0/5............. 

 10%|▉         | 78/795 [00:59<09:01,  1.32it/s]

Loss: 0.0279
acc: 0.9911615328804169
Epoch: 0/5............. 

 10%|▉         | 79/795 [01:00<09:00,  1.33it/s]

Loss: 0.0291
acc: 0.9900956630497245
Epoch: 0/5............. 

 10%|█         | 80/795 [01:00<08:56,  1.33it/s]

Loss: 0.0280
acc: 0.9907330279050396
Epoch: 0/5............. 

 10%|█         | 81/795 [01:01<08:56,  1.33it/s]

Loss: 0.0317
acc: 0.9900391102419946
Epoch: 0/5............. 

 10%|█         | 82/795 [01:02<08:56,  1.33it/s]

Loss: 0.0288
acc: 0.9905362776025236
Epoch: 0/5............. 

 10%|█         | 83/795 [01:03<08:54,  1.33it/s]

Loss: 0.0275
acc: 0.9909228441754917
Epoch: 0/5............. 

 11%|█         | 84/795 [01:03<08:49,  1.34it/s]

Loss: 0.0293
acc: 0.990952175786299
Epoch: 0/5............. 

 11%|█         | 85/795 [01:04<08:50,  1.34it/s]

Loss: 0.0239
acc: 0.99213185665809
Epoch: 0/5............. 

 11%|█         | 86/795 [01:05<08:48,  1.34it/s]

Loss: 0.0321
acc: 0.990080956895923
Epoch: 0/5............. 

 11%|█         | 87/795 [01:06<08:44,  1.35it/s]

Loss: 0.0283
acc: 0.9898903132020616
Epoch: 0/5............. 

 11%|█         | 88/795 [01:06<08:45,  1.35it/s]

Loss: 0.0268
acc: 0.9915406698564593
Epoch: 0/5............. 

 11%|█         | 89/795 [01:07<08:44,  1.35it/s]

Loss: 0.0327
acc: 0.9891614906832298
Epoch: 0/5............. 

 11%|█▏        | 90/795 [01:08<08:43,  1.35it/s]

Loss: 0.0236
acc: 0.9922352248472804
Epoch: 0/5............. 

 11%|█▏        | 91/795 [01:09<08:41,  1.35it/s]

Loss: 0.0272
acc: 0.9915931063472047
Epoch: 0/5............. 

 12%|█▏        | 92/795 [01:09<08:43,  1.34it/s]

Loss: 0.0304
acc: 0.9898566308243728
Epoch: 0/5............. 

 12%|█▏        | 93/795 [01:10<08:39,  1.35it/s]

Loss: 0.0323
acc: 0.9887826597176682
Epoch: 0/5............. 

 12%|█▏        | 94/795 [01:11<08:40,  1.35it/s]

Loss: 0.0263
acc: 0.991280711663372
Epoch: 0/5............. 

 12%|█▏        | 95/795 [01:12<08:38,  1.35it/s]

Loss: 0.0242
acc: 0.9921949432026383
Epoch: 0/5............. 

 12%|█▏        | 96/795 [01:12<08:38,  1.35it/s]

Loss: 0.0302
acc: 0.9904608826304203
Epoch: 0/5............. 

 12%|█▏        | 97/795 [01:13<08:37,  1.35it/s]

Loss: 0.0304
acc: 0.990139211136891
Epoch: 0/5............. 

 12%|█▏        | 98/795 [01:14<08:38,  1.34it/s]

Loss: 0.0297
acc: 0.9911443530291698
Epoch: 0/5............. 

 12%|█▏        | 99/795 [01:15<08:37,  1.35it/s]

Loss: 0.0266
acc: 0.9909969640925428
Epoch: 0/5............. 

 13%|█▎        | 100/795 [01:15<08:36,  1.35it/s]

Loss: 0.0271
acc: 0.9907188297120378
Epoch: 0/5............. 

 13%|█▎        | 101/795 [01:16<08:35,  1.35it/s]

Loss: 0.0263
acc: 0.9914185371812491
Epoch: 0/5............. 

 13%|█▎        | 102/795 [01:17<08:35,  1.34it/s]

Loss: 0.0297
acc: 0.9896513404639533
Epoch: 0/5............. 

 13%|█▎        | 103/795 [01:18<08:34,  1.34it/s]

Loss: 0.0259
acc: 0.9915315383739035
Epoch: 0/5............. 

 13%|█▎        | 104/795 [01:18<08:31,  1.35it/s]

Loss: 0.0260
acc: 0.9921074786024976
Epoch: 0/5............. 

 13%|█▎        | 105/795 [01:19<08:32,  1.35it/s]

Loss: 0.0323
acc: 0.9897993879632778
Epoch: 0/5............. 

 13%|█▎        | 106/795 [01:20<08:31,  1.35it/s]

Loss: 0.0274
acc: 0.9917765393502787
Epoch: 0/5............. 

 13%|█▎        | 107/795 [01:20<08:30,  1.35it/s]

Loss: 0.0266
acc: 0.9913472108940034
Epoch: 0/5............. 

 14%|█▎        | 108/795 [01:21<08:30,  1.35it/s]

Loss: 0.0260
acc: 0.9919354838709677
Epoch: 0/5............. 

 14%|█▎        | 109/795 [01:22<08:28,  1.35it/s]

Loss: 0.0290
acc: 0.99109930255729
Epoch: 0/5............. 

 14%|█▍        | 110/795 [01:23<08:30,  1.34it/s]

Loss: 0.0266
acc: 0.9915298729480942
Epoch: 0/5............. 

 14%|█▍        | 111/795 [01:23<08:29,  1.34it/s]

Loss: 0.0309
acc: 0.9894082511459925
Epoch: 0/5............. 

 14%|█▍        | 112/795 [01:24<08:30,  1.34it/s]

Loss: 0.0275
acc: 0.9906000424058238
Epoch: 0/5............. 

 14%|█▍        | 113/795 [01:25<08:29,  1.34it/s]

Loss: 0.0270
acc: 0.9914112554112554
Epoch: 0/5............. 

 14%|█▍        | 114/795 [01:26<08:25,  1.35it/s]

Loss: 0.0297
acc: 0.991389913899139
Epoch: 0/5............. 

 14%|█▍        | 115/795 [01:26<08:27,  1.34it/s]

Loss: 0.0271
acc: 0.9913778117720683
Epoch: 0/5............. 

 15%|█▍        | 116/795 [01:27<08:25,  1.34it/s]

Loss: 0.0308
acc: 0.9908805140073923
Epoch: 0/5............. 

 15%|█▍        | 117/795 [01:28<08:26,  1.34it/s]

Loss: 0.0267
acc: 0.9920096021947874
Epoch: 0/5............. 

 15%|█▍        | 118/795 [01:29<08:24,  1.34it/s]

Loss: 0.0235
acc: 0.9923490406874093
Epoch: 0/5............. 

 15%|█▍        | 119/795 [01:29<08:24,  1.34it/s]

Loss: 0.0279
acc: 0.9911193208056552
Epoch: 0/5............. 

 15%|█▌        | 120/795 [01:30<08:21,  1.35it/s]

Loss: 0.0340
acc: 0.9890601690701144
Epoch: 0/5............. 

 15%|█▌        | 121/795 [01:31<08:22,  1.34it/s]

Loss: 0.0268
acc: 0.9911092294665538
Epoch: 0/5............. 

 15%|█▌        | 122/795 [01:32<08:21,  1.34it/s]

Loss: 0.0331
acc: 0.9902662669723152
Epoch: 0/5............. 

 15%|█▌        | 123/795 [01:32<08:21,  1.34it/s]

Loss: 0.0287
acc: 0.9907089923681008
Epoch: 0/5............. 

 16%|█▌        | 124/795 [01:33<08:21,  1.34it/s]

Loss: 0.0266
acc: 0.99240251759711
Epoch: 0/5............. 

 16%|█▌        | 125/795 [01:34<08:22,  1.33it/s]

Loss: 0.0290
acc: 0.9898920616584239
Epoch: 0/5............. 

 16%|█▌        | 126/795 [01:35<08:21,  1.33it/s]

Loss: 0.0298
acc: 0.9902471834538423
Epoch: 0/5............. 

 16%|█▌        | 127/795 [01:35<08:21,  1.33it/s]

Loss: 0.0288
acc: 0.9911351430883543
Epoch: 0/5............. 

 16%|█▌        | 128/795 [01:36<08:20,  1.33it/s]

Loss: 0.0326
acc: 0.9905500705218617
Epoch: 0/5............. 

 16%|█▌        | 129/795 [01:37<08:18,  1.34it/s]

Loss: 0.0304
acc: 0.9905657006039381
Epoch: 0/5............. 

 16%|█▋        | 130/795 [01:38<08:18,  1.33it/s]

Loss: 0.0270
acc: 0.9910224068852945
Epoch: 0/5............. 

 16%|█▋        | 131/795 [01:38<08:19,  1.33it/s]

Loss: 0.0271
acc: 0.9907921462423832
Epoch: 0/5............. 

 17%|█▋        | 132/795 [01:39<08:21,  1.32it/s]

Loss: 0.0270
acc: 0.9916255171493393
Epoch: 0/5............. 

 17%|█▋        | 133/795 [01:40<08:19,  1.32it/s]

Loss: 0.0303
acc: 0.990314248816186
Epoch: 0/5............. 

 17%|█▋        | 134/795 [01:41<08:20,  1.32it/s]

Loss: 0.0274
acc: 0.9910997033234441
Epoch: 0/5............. 

 17%|█▋        | 135/795 [01:41<08:20,  1.32it/s]

Loss: 0.0262
acc: 0.9917817561807332
Epoch: 0/5............. 

 17%|█▋        | 136/795 [01:42<08:19,  1.32it/s]

Loss: 0.0260
acc: 0.9918929583527639
Epoch: 0/5............. 

 17%|█▋        | 137/795 [01:43<08:17,  1.32it/s]

Loss: 0.0250
acc: 0.9917993079584775
Epoch: 0/5............. 

 17%|█▋        | 138/795 [01:44<08:18,  1.32it/s]

Loss: 0.0305
acc: 0.9902417311511333
Epoch: 0/5............. 

 17%|█▋        | 139/795 [01:44<08:16,  1.32it/s]

Loss: 0.0256
acc: 0.9924258289703316
Epoch: 0/5............. 

 18%|█▊        | 140/795 [01:45<08:16,  1.32it/s]

Loss: 0.0325
acc: 0.990058024341919
Epoch: 0/5............. 

 18%|█▊        | 141/795 [01:46<08:17,  1.31it/s]

Loss: 0.0271
acc: 0.9908339386392723
Epoch: 0/5............. 

 18%|█▊        | 142/795 [01:47<08:15,  1.32it/s]

Loss: 0.0332
acc: 0.9899562104677834
Epoch: 0/5............. 

 18%|█▊        | 143/795 [01:48<08:16,  1.31it/s]

Loss: 0.0330
acc: 0.9891392610637434
Epoch: 0/5............. 

 18%|█▊        | 144/795 [01:48<08:14,  1.32it/s]

Loss: 0.0295
acc: 0.9902809683689697
Epoch: 0/5............. 

 18%|█▊        | 145/795 [01:49<08:13,  1.32it/s]

Loss: 0.0295
acc: 0.9904276157741065
Epoch: 0/5............. 

 18%|█▊        | 146/795 [01:50<08:14,  1.31it/s]

Loss: 0.0323
acc: 0.9891015832370483
Epoch: 0/5............. 

 18%|█▊        | 147/795 [01:51<08:14,  1.31it/s]

Loss: 0.0363
acc: 0.9893443555420728
Epoch: 0/5............. 

 19%|█▊        | 148/795 [01:51<08:14,  1.31it/s]

Loss: 0.0332
acc: 0.9890549044168083
Epoch: 0/5............. 

 19%|█▊        | 149/795 [01:52<08:13,  1.31it/s]

Loss: 0.0332
acc: 0.9886653036335593
Epoch: 0/5............. 

 19%|█▉        | 150/795 [01:53<08:13,  1.31it/s]

Loss: 0.0304
acc: 0.9909262356332064
Epoch: 0/5............. 

 19%|█▉        | 151/795 [01:54<08:09,  1.32it/s]

Loss: 0.0344
acc: 0.9886066095817706
Epoch: 0/5............. 

 19%|█▉        | 152/795 [01:54<08:10,  1.31it/s]

Loss: 0.0310
acc: 0.9896569737071217
Epoch: 0/5............. 

 19%|█▉        | 153/795 [01:55<08:10,  1.31it/s]

Loss: 0.0265
acc: 0.9913710108753788
Epoch: 0/5............. 

 19%|█▉        | 154/795 [01:56<08:10,  1.31it/s]

Loss: 0.0275
acc: 0.9917652343165144
Epoch: 0/5............. 

 19%|█▉        | 155/795 [01:57<08:08,  1.31it/s]

Loss: 0.0293
acc: 0.9905645640016246
Epoch: 0/5............. 

 20%|█▉        | 156/795 [01:57<08:06,  1.31it/s]

Loss: 0.0312
acc: 0.9888259462151394
Epoch: 0/5............. 

 20%|█▉        | 157/795 [01:58<08:05,  1.31it/s]

Loss: 0.0309
acc: 0.9890912697100922
Epoch: 0/5............. 

 20%|█▉        | 158/795 [01:59<08:03,  1.32it/s]

Loss: 0.0217
acc: 0.99294621979735
Epoch: 0/5............. 

 20%|██        | 159/795 [02:00<08:00,  1.32it/s]

Loss: 0.0269
acc: 0.9914396246604659
Epoch: 0/5............. 

 20%|██        | 160/795 [02:00<08:02,  1.32it/s]

Loss: 0.0307
acc: 0.9898920808633531
Epoch: 0/5............. 

 20%|██        | 161/795 [02:01<07:59,  1.32it/s]

Loss: 0.0258
acc: 0.9915126019410311
Epoch: 0/5............. 

 20%|██        | 162/795 [02:02<07:58,  1.32it/s]

Loss: 0.0302
acc: 0.989548919949174
Epoch: 0/5............. 

 21%|██        | 163/795 [02:03<07:58,  1.32it/s]

Loss: 0.0251
acc: 0.9917031332049712
Epoch: 0/5............. 

 21%|██        | 164/795 [02:04<07:59,  1.32it/s]

Loss: 0.0253
acc: 0.9918374685364977
Epoch: 0/5............. 

 21%|██        | 165/795 [02:04<07:59,  1.31it/s]

Loss: 0.0304
acc: 0.9902246772591857
Epoch: 0/5............. 

 21%|██        | 166/795 [02:05<08:00,  1.31it/s]

Loss: 0.0300
acc: 0.989711998499015
Epoch: 0/5............. 

 21%|██        | 167/795 [02:06<07:59,  1.31it/s]

Loss: 0.0251
acc: 0.9924421176817578
Epoch: 0/5............. 

 21%|██        | 168/795 [02:07<07:56,  1.31it/s]

Loss: 0.0284
acc: 0.9905560990292723
Epoch: 0/5............. 

 21%|██▏       | 169/795 [02:07<07:57,  1.31it/s]

Loss: 0.0243
acc: 0.991475433422056
Epoch: 0/5............. 

 21%|██▏       | 170/795 [02:08<07:54,  1.32it/s]

Loss: 0.0291
acc: 0.9909000733169449
Epoch: 0/5............. 

 22%|██▏       | 171/795 [02:09<07:52,  1.32it/s]

Loss: 0.0237
acc: 0.9923702106485321
Epoch: 0/5............. 

 22%|██▏       | 172/795 [02:10<07:50,  1.32it/s]

Loss: 0.0258
acc: 0.9915878390170687
Epoch: 0/5............. 

 22%|██▏       | 173/795 [02:10<07:51,  1.32it/s]

Loss: 0.0294
acc: 0.990517001944213
Epoch: 0/5............. 

 22%|██▏       | 174/795 [02:11<07:48,  1.33it/s]

Loss: 0.0281
acc: 0.9908027899343544
Epoch: 0/5............. 

 22%|██▏       | 175/795 [02:12<07:48,  1.32it/s]

Loss: 0.0375
acc: 0.98758487551591
Epoch: 0/5............. 

 22%|██▏       | 176/795 [02:13<07:48,  1.32it/s]

Loss: 0.0316
acc: 0.98973954222573
Epoch: 0/5............. 

 22%|██▏       | 177/795 [02:13<07:44,  1.33it/s]

Loss: 0.0254
acc: 0.9917598189861876
Epoch: 0/5............. 

 22%|██▏       | 178/795 [02:14<07:45,  1.33it/s]

Loss: 0.0323
acc: 0.9885796325904657
Epoch: 0/5............. 

 23%|██▎       | 179/795 [02:15<07:45,  1.32it/s]

Loss: 0.0308
acc: 0.9901823748668797
Epoch: 0/5............. 

 23%|██▎       | 180/795 [02:16<07:45,  1.32it/s]

Loss: 0.0316
acc: 0.9903126831454476
Epoch: 0/5............. 

 23%|██▎       | 181/795 [02:16<07:43,  1.33it/s]

Loss: 0.0269
acc: 0.9907800558049253
Epoch: 0/5............. 

 23%|██▎       | 182/795 [02:17<07:42,  1.33it/s]

Loss: 0.0281
acc: 0.9906650671065457
Epoch: 0/5............. 

 23%|██▎       | 183/795 [02:18<07:40,  1.33it/s]

Loss: 0.0291
acc: 0.9902135893428593
Epoch: 0/5............. 

 23%|██▎       | 184/795 [02:19<07:41,  1.32it/s]

Loss: 0.0343
acc: 0.9894643310484894
Epoch: 0/5............. 

 23%|██▎       | 185/795 [02:19<07:39,  1.33it/s]

Loss: 0.0344
acc: 0.9887777589421936
Epoch: 0/5............. 

 23%|██▎       | 186/795 [02:20<07:39,  1.33it/s]

Loss: 0.0305
acc: 0.9903295259643105
Epoch: 0/5............. 

 24%|██▎       | 187/795 [02:21<07:39,  1.32it/s]

Loss: 0.0279
acc: 0.9910814870446865
Epoch: 0/5............. 

 24%|██▎       | 188/795 [02:22<07:38,  1.32it/s]

Loss: 0.0304
acc: 0.9903607626337798
Epoch: 0/5............. 

 24%|██▍       | 189/795 [02:22<07:36,  1.33it/s]

Loss: 0.0278
acc: 0.9900967668856597
Epoch: 0/5............. 

 24%|██▍       | 190/795 [02:23<07:36,  1.33it/s]

Loss: 0.0318
acc: 0.9903891488049904
Epoch: 0/5............. 

 24%|██▍       | 191/795 [02:24<07:34,  1.33it/s]

Loss: 0.0280
acc: 0.9896895317970222
Epoch: 0/5............. 

 24%|██▍       | 192/795 [02:25<07:34,  1.33it/s]

Loss: 0.0371
acc: 0.9891770471717378
Epoch: 0/5............. 

 24%|██▍       | 193/795 [02:25<07:33,  1.33it/s]

Loss: 0.0272
acc: 0.9911931708447603
Epoch: 0/5............. 

 24%|██▍       | 194/795 [02:26<07:34,  1.32it/s]

Loss: 0.0291
acc: 0.9913832680015539
Epoch: 0/5............. 

 25%|██▍       | 195/795 [02:27<07:32,  1.33it/s]

Loss: 0.0275
acc: 0.9904598490048044
Epoch: 0/5............. 

 25%|██▍       | 196/795 [02:28<07:31,  1.33it/s]

Loss: 0.0325
acc: 0.9890636144414632
Epoch: 0/5............. 

 25%|██▍       | 197/795 [02:28<07:30,  1.33it/s]

Loss: 0.0247
acc: 0.9920540997464075
Epoch: 0/5............. 

 25%|██▍       | 198/795 [02:29<07:30,  1.33it/s]

Loss: 0.0275
acc: 0.9913569302855696
Epoch: 0/5............. 

 25%|██▌       | 199/795 [02:30<07:28,  1.33it/s]

Loss: 0.0401
acc: 0.9874241751738423
Epoch: 0/5............. 

 25%|██▌       | 200/795 [02:31<07:26,  1.33it/s]

Loss: 0.0281
acc: 0.991116795133248
Epoch: 0/5............. 

 25%|██▌       | 201/795 [02:31<07:26,  1.33it/s]

Loss: 0.0297
acc: 0.9900294584183096
Epoch: 0/5............. 

 25%|██▌       | 202/795 [02:32<07:25,  1.33it/s]

Loss: 0.0338
acc: 0.9890185548555889
Epoch: 0/5............. 

 26%|██▌       | 203/795 [02:33<07:25,  1.33it/s]

Loss: 0.0337
acc: 0.9883333917247662
Epoch: 0/5............. 

 26%|██▌       | 204/795 [02:34<07:24,  1.33it/s]

Loss: 0.0250
acc: 0.9914953933380581
Epoch: 0/5............. 

 26%|██▌       | 205/795 [02:34<07:24,  1.33it/s]

Loss: 0.0261
acc: 0.9919661583306673
Epoch: 0/5............. 

 26%|██▌       | 206/795 [02:35<07:23,  1.33it/s]

Loss: 0.0267
acc: 0.9914251414851655
Epoch: 0/5............. 

 26%|██▌       | 207/795 [02:36<07:21,  1.33it/s]

Loss: 0.0288
acc: 0.9906994700452743
Epoch: 0/5............. 

 26%|██▌       | 208/795 [02:37<07:22,  1.33it/s]

Loss: 0.0260
acc: 0.9913902555149976
Epoch: 0/5............. 

 26%|██▋       | 209/795 [02:37<07:22,  1.33it/s]

Loss: 0.0311
acc: 0.9892426339727111
Epoch: 0/5............. 

 26%|██▋       | 210/795 [02:38<07:20,  1.33it/s]

Loss: 0.0250
acc: 0.9914615285474933
Epoch: 0/5............. 

 27%|██▋       | 211/795 [02:39<07:18,  1.33it/s]

Loss: 0.0262
acc: 0.9916064948869259
Epoch: 0/5............. 

 27%|██▋       | 212/795 [02:40<07:18,  1.33it/s]

Loss: 0.0272
acc: 0.9911904761904762
Epoch: 0/5............. 

 27%|██▋       | 213/795 [02:40<07:18,  1.33it/s]

Loss: 0.0259
acc: 0.9915367797446929
Epoch: 0/5............. 

 27%|██▋       | 214/795 [02:41<07:17,  1.33it/s]

Loss: 0.0386
acc: 0.9876376800431333
Epoch: 0/5............. 

 27%|██▋       | 215/795 [02:42<07:16,  1.33it/s]

Loss: 0.0291
acc: 0.9908851529268786
Epoch: 0/5............. 

 27%|██▋       | 216/795 [02:43<07:12,  1.34it/s]

Loss: 0.0340
acc: 0.9893143067698389
Epoch: 0/5............. 

 27%|██▋       | 217/795 [02:43<07:13,  1.33it/s]

Loss: 0.0305
acc: 0.9906188586896066
Epoch: 0/5............. 

 27%|██▋       | 218/795 [02:44<07:13,  1.33it/s]

Loss: 0.0276
acc: 0.9907631470223691
Epoch: 0/5............. 

 28%|██▊       | 219/795 [02:45<07:10,  1.34it/s]

Loss: 0.0329
acc: 0.9895772806507844
Epoch: 0/5............. 

 28%|██▊       | 220/795 [02:46<07:11,  1.33it/s]

Loss: 0.0297
acc: 0.9899878745886022
Epoch: 0/5............. 

 28%|██▊       | 221/795 [02:46<07:10,  1.33it/s]

Loss: 0.0283
acc: 0.991083610978899
Epoch: 0/5............. 

 28%|██▊       | 222/795 [02:47<07:09,  1.33it/s]

Loss: 0.0256
acc: 0.9915567101934778
Epoch: 0/5............. 

 28%|██▊       | 223/795 [02:48<07:09,  1.33it/s]

Loss: 0.0276
acc: 0.9909888862930948
Epoch: 0/5............. 

 28%|██▊       | 224/795 [02:49<07:08,  1.33it/s]

Loss: 0.0262
acc: 0.990302735393278
Epoch: 0/5............. 

 28%|██▊       | 225/795 [02:49<07:07,  1.33it/s]

Loss: 0.0289
acc: 0.9903676974920228
Epoch: 0/5............. 

 28%|██▊       | 226/795 [02:50<07:07,  1.33it/s]

Loss: 0.0272
acc: 0.9915858668857848
Epoch: 0/5............. 

 29%|██▊       | 227/795 [02:51<07:07,  1.33it/s]

Loss: 0.0268
acc: 0.9908609409076747
Epoch: 0/5............. 

 29%|██▊       | 228/795 [02:52<07:06,  1.33it/s]

Loss: 0.0278
acc: 0.9904221497846996
Epoch: 0/5............. 

 29%|██▉       | 229/795 [02:52<07:04,  1.33it/s]

Loss: 0.0307
acc: 0.9905444126074499
Epoch: 0/5............. 

 29%|██▉       | 230/795 [02:53<07:04,  1.33it/s]

Loss: 0.0305
acc: 0.9893539976825029
Epoch: 0/5............. 

 29%|██▉       | 231/795 [02:54<07:02,  1.34it/s]

Loss: 0.0270
acc: 0.9909421634865246
Epoch: 0/5............. 

 29%|██▉       | 232/795 [02:55<07:02,  1.33it/s]

Loss: 0.0266
acc: 0.9912428065911284
Epoch: 0/5............. 

 29%|██▉       | 233/795 [02:55<07:00,  1.34it/s]

Loss: 0.0306
acc: 0.9904476320019785
Epoch: 0/5............. 

 29%|██▉       | 234/795 [02:56<06:59,  1.34it/s]

Loss: 0.0272
acc: 0.9902312528862207
Epoch: 0/5............. 

 30%|██▉       | 235/795 [02:57<06:58,  1.34it/s]

Loss: 0.0328
acc: 0.9896229474366911
Epoch: 0/5............. 

 30%|██▉       | 236/795 [02:58<06:59,  1.33it/s]

Loss: 0.0277
acc: 0.9918597760658703
Epoch: 0/5............. 

 30%|██▉       | 237/795 [02:58<06:59,  1.33it/s]

Loss: 0.0326
acc: 0.9893358022151356
Epoch: 0/5............. 

 30%|██▉       | 238/795 [02:59<06:57,  1.33it/s]

Loss: 0.0308
acc: 0.9903666325558418
Epoch: 0/5............. 

 30%|███       | 239/795 [03:00<06:58,  1.33it/s]

Loss: 0.0263
acc: 0.9917569659442724
Epoch: 0/5............. 

 30%|███       | 240/795 [03:01<06:58,  1.33it/s]

Loss: 0.0309
acc: 0.9896860359415426
Epoch: 0/5............. 

 30%|███       | 241/795 [03:02<06:56,  1.33it/s]

Loss: 0.0308
acc: 0.9895036158112757
Epoch: 0/5............. 

 30%|███       | 242/795 [03:02<06:56,  1.33it/s]

Loss: 0.0331
acc: 0.9892738637240528
Epoch: 0/5............. 

 31%|███       | 243/795 [03:03<06:55,  1.33it/s]

Loss: 0.0315
acc: 0.989536
Epoch: 0/5............. 

 31%|███       | 244/795 [03:04<06:55,  1.32it/s]

Loss: 0.0316
acc: 0.9902502329295887
Epoch: 0/5............. 

 31%|███       | 245/795 [03:05<06:54,  1.33it/s]

Loss: 0.0239
acc: 0.9923691860465116
Epoch: 0/5............. 

 31%|███       | 246/795 [03:05<06:53,  1.33it/s]

Loss: 0.0289
acc: 0.9907167192823431
Epoch: 0/5............. 

 31%|███       | 247/795 [03:06<06:53,  1.33it/s]

Loss: 0.0251
acc: 0.9917205692108667
Epoch: 0/5............. 

 31%|███       | 248/795 [03:07<06:50,  1.33it/s]

Loss: 0.0259
acc: 0.9924824211788341
Epoch: 0/5............. 

 31%|███▏      | 249/795 [03:08<06:50,  1.33it/s]

Loss: 0.0238
acc: 0.9924286305337194
Epoch: 0/5............. 

 31%|███▏      | 250/795 [03:08<06:50,  1.33it/s]

Loss: 0.0314
acc: 0.9896034457151344
Epoch: 0/5............. 

 32%|███▏      | 251/795 [03:09<06:50,  1.33it/s]

Loss: 0.0304
acc: 0.9898495691543742
Epoch: 0/5............. 

 32%|███▏      | 252/795 [03:10<06:50,  1.32it/s]

Loss: 0.0266
acc: 0.9918351197755557
Epoch: 0/5............. 

 32%|███▏      | 253/795 [03:11<06:48,  1.33it/s]

Loss: 0.0342
acc: 0.9882462624446442
Epoch: 0/5............. 

 32%|███▏      | 254/795 [03:11<06:48,  1.32it/s]

Loss: 0.0348
acc: 0.9881793905120955
Epoch: 0/5............. 

 32%|███▏      | 255/795 [03:12<06:46,  1.33it/s]

Loss: 0.0250
acc: 0.9917767059381671
Epoch: 0/5............. 

 32%|███▏      | 256/795 [03:13<06:45,  1.33it/s]

Loss: 0.0332
acc: 0.9882944207646797
Epoch: 0/5............. 

 32%|███▏      | 257/795 [03:14<06:45,  1.33it/s]

Loss: 0.0311
acc: 0.9906726858933701
Epoch: 0/5............. 

 32%|███▏      | 258/795 [03:14<06:43,  1.33it/s]

Loss: 0.0366
acc: 0.9883029598035414
Epoch: 0/5............. 

 33%|███▎      | 259/795 [03:15<06:41,  1.34it/s]

Loss: 0.0251
acc: 0.9922172136920693
Epoch: 0/5............. 

 33%|███▎      | 260/795 [03:16<06:40,  1.34it/s]

Loss: 0.0280
acc: 0.990612979496771
Epoch: 0/5............. 

 33%|███▎      | 261/795 [03:17<06:42,  1.33it/s]

Loss: 0.0282
acc: 0.9912944738834216
Epoch: 0/5............. 

 33%|███▎      | 262/795 [03:17<06:41,  1.33it/s]

Loss: 0.0316
acc: 0.9892330383480826
Epoch: 0/5............. 

 33%|███▎      | 263/795 [03:18<06:41,  1.32it/s]

Loss: 0.0282
acc: 0.9911975909196201
Epoch: 0/5............. 

 33%|███▎      | 264/795 [03:19<06:40,  1.33it/s]

Loss: 0.0268
acc: 0.9910373147652205
Epoch: 0/5............. 

 33%|███▎      | 265/795 [03:20<06:39,  1.33it/s]

Loss: 0.0263
acc: 0.9917053187527508
Epoch: 0/5............. 

 33%|███▎      | 266/795 [03:20<06:40,  1.32it/s]

Loss: 0.0308
acc: 0.9900804289544236
Epoch: 0/5............. 

 34%|███▎      | 267/795 [03:21<06:38,  1.33it/s]

Loss: 0.0312
acc: 0.9893837987537503
Epoch: 0/5............. 

 34%|███▎      | 268/795 [03:22<06:38,  1.32it/s]

Loss: 0.0305
acc: 0.990132004658988
Epoch: 0/5............. 

 34%|███▍      | 269/795 [03:23<06:38,  1.32it/s]

Loss: 0.0271
acc: 0.9914071944326461
Epoch: 0/5............. 

 34%|███▍      | 270/795 [03:23<06:35,  1.33it/s]

Loss: 0.0257
acc: 0.9910484581497797
Epoch: 0/5............. 

 34%|███▍      | 271/795 [03:24<06:35,  1.33it/s]

Loss: 0.0327
acc: 0.9893968648754786
Epoch: 0/5............. 

 34%|███▍      | 272/795 [03:25<06:35,  1.32it/s]

Loss: 0.0310
acc: 0.9902643547470154
Epoch: 0/5............. 

 34%|███▍      | 273/795 [03:26<06:34,  1.32it/s]

Loss: 0.0267
acc: 0.9919367224696667
Epoch: 0/5............. 

 34%|███▍      | 274/795 [03:26<06:32,  1.33it/s]

Loss: 0.0286
acc: 0.9910635523338319
Epoch: 0/5............. 

 35%|███▍      | 275/795 [03:27<06:32,  1.32it/s]

Loss: 0.0285
acc: 0.9897546248715313
Epoch: 0/5............. 

 35%|███▍      | 276/795 [03:28<06:31,  1.32it/s]

Loss: 0.0263
acc: 0.9911440516913721
Epoch: 0/5............. 

 35%|███▍      | 277/795 [03:29<06:30,  1.33it/s]

Loss: 0.0276
acc: 0.9913000071311417
Epoch: 0/5............. 

 35%|███▍      | 278/795 [03:29<06:30,  1.32it/s]

Loss: 0.0276
acc: 0.9916052823677749
Epoch: 0/5............. 

 35%|███▌      | 279/795 [03:30<06:30,  1.32it/s]

Loss: 0.0300
acc: 0.9898377262315708
Epoch: 0/5............. 

 35%|███▌      | 280/795 [03:31<06:29,  1.32it/s]

Loss: 0.0343
acc: 0.9887192230977995
Epoch: 0/5............. 

 35%|███▌      | 281/795 [03:32<06:29,  1.32it/s]

Loss: 0.0271
acc: 0.9924017984733888
Epoch: 0/5............. 

 35%|███▌      | 282/795 [03:32<06:27,  1.32it/s]

Loss: 0.0253
acc: 0.9921105801609955
Epoch: 0/5............. 

 36%|███▌      | 283/795 [03:33<06:27,  1.32it/s]

Loss: 0.0277
acc: 0.9906928297829447
Epoch: 0/5............. 

 36%|███▌      | 284/795 [03:34<06:27,  1.32it/s]

Loss: 0.0295
acc: 0.9904914492703145
Epoch: 0/5............. 

 36%|███▌      | 285/795 [03:35<06:26,  1.32it/s]

Loss: 0.0280
acc: 0.9911126910771418
Epoch: 0/5............. 

 36%|███▌      | 286/795 [03:35<06:25,  1.32it/s]

Loss: 0.0280
acc: 0.991220186657449
Epoch: 0/5............. 

 36%|███▌      | 287/795 [03:36<06:23,  1.32it/s]

Loss: 0.0261
acc: 0.9920563278570139
Epoch: 0/5............. 

 36%|███▌      | 288/795 [03:37<06:22,  1.33it/s]

Loss: 0.0251
acc: 0.9916917167668671
Epoch: 0/5............. 

 36%|███▋      | 289/795 [03:38<06:22,  1.32it/s]

Loss: 0.0314
acc: 0.9895196816825351
Epoch: 0/5............. 

 36%|███▋      | 290/795 [03:38<06:21,  1.32it/s]

Loss: 0.0288
acc: 0.9907510409051902
Epoch: 0/5............. 

 37%|███▋      | 291/795 [03:39<06:20,  1.32it/s]

Loss: 0.0263
acc: 0.9912565743191183
Epoch: 0/5............. 

 37%|███▋      | 292/795 [03:40<06:19,  1.33it/s]

Loss: 0.0289
acc: 0.9911673938491008
Epoch: 0/5............. 

 37%|███▋      | 293/795 [03:41<06:18,  1.33it/s]

Loss: 0.0323
acc: 0.9897924464103437
Epoch: 0/5............. 

 37%|███▋      | 294/795 [03:42<06:18,  1.32it/s]

Loss: 0.0284
acc: 0.9906268538659284
Epoch: 0/5............. 

 37%|███▋      | 295/795 [03:42<06:17,  1.32it/s]

Loss: 0.0267
acc: 0.9912244973525383
Epoch: 0/5............. 

 37%|███▋      | 296/795 [03:43<06:18,  1.32it/s]

Loss: 0.0282
acc: 0.9915456100915893
Epoch: 0/5............. 

 37%|███▋      | 297/795 [03:44<06:17,  1.32it/s]

Loss: 0.0270
acc: 0.9910616812227074
Epoch: 0/5............. 

 37%|███▋      | 298/795 [03:45<06:17,  1.32it/s]

Loss: 0.0323
acc: 0.9892877412031782
Epoch: 0/5............. 

 38%|███▊      | 299/795 [03:45<06:15,  1.32it/s]

Loss: 0.0281
acc: 0.9909251659827177
Epoch: 0/5............. 

 38%|███▊      | 300/795 [03:46<06:14,  1.32it/s]

Loss: 0.0257
acc: 0.9910724333245808
Epoch: 0/5............. 

 38%|███▊      | 301/795 [03:47<06:14,  1.32it/s]

Loss: 0.0313
acc: 0.9893418341061309
Epoch: 0/5............. 

 38%|███▊      | 302/795 [03:48<06:14,  1.32it/s]

Loss: 0.0259
acc: 0.991418786316235
Epoch: 0/5............. 

 38%|███▊      | 303/795 [03:48<06:13,  1.32it/s]

Loss: 0.0311
acc: 0.989567907328792
Epoch: 0/5............. 

 38%|███▊      | 304/795 [03:49<06:13,  1.32it/s]

Loss: 0.0351
acc: 0.9890143116307196
Epoch: 0/5............. 

 38%|███▊      | 305/795 [03:50<06:12,  1.32it/s]

Loss: 0.0307
acc: 0.9889410426000995
Epoch: 0/5............. 

 38%|███▊      | 306/795 [03:51<06:12,  1.31it/s]

Loss: 0.0295
acc: 0.9909594156375905
Epoch: 0/5............. 

 39%|███▊      | 307/795 [03:51<06:10,  1.32it/s]

Loss: 0.0285
acc: 0.9902643499425327
Epoch: 0/5............. 

 39%|███▊      | 308/795 [03:52<06:10,  1.31it/s]

Loss: 0.0262
acc: 0.9912383801688215
Epoch: 0/5............. 

 39%|███▉      | 309/795 [03:53<06:10,  1.31it/s]

Loss: 0.0315
acc: 0.9897561831257674
Epoch: 0/5............. 

 39%|███▉      | 310/795 [03:54<06:08,  1.32it/s]

Loss: 0.0300
acc: 0.9903009662014586
Epoch: 0/5............. 

 39%|███▉      | 311/795 [03:54<06:07,  1.32it/s]

Loss: 0.0300
acc: 0.9900333270452116
Epoch: 0/5............. 

 39%|███▉      | 312/795 [03:55<06:07,  1.31it/s]

Loss: 0.0286
acc: 0.989833510449876
Epoch: 0/5............. 

 39%|███▉      | 313/795 [03:56<06:06,  1.31it/s]

Loss: 0.0312
acc: 0.9895117807814462
Epoch: 0/5............. 

 39%|███▉      | 314/795 [03:57<06:05,  1.31it/s]

Loss: 0.0269
acc: 0.9903792912513842
Epoch: 0/5............. 

 40%|███▉      | 315/795 [03:57<06:03,  1.32it/s]

Loss: 0.0300
acc: 0.9901550655804737
Epoch: 0/5............. 

 40%|███▉      | 316/795 [03:58<06:02,  1.32it/s]

Loss: 0.0263
acc: 0.9915096367414201
Epoch: 0/5............. 

 40%|███▉      | 317/795 [03:59<06:01,  1.32it/s]

Loss: 0.0291
acc: 0.9902953106637856
Epoch: 0/5............. 

 40%|████      | 318/795 [04:00<06:00,  1.32it/s]

Loss: 0.0303
acc: 0.9899067802293608
Epoch: 0/5............. 

 40%|████      | 319/795 [04:00<05:59,  1.32it/s]

Loss: 0.0293
acc: 0.9907453906306047
Epoch: 0/5............. 

 40%|████      | 320/795 [04:01<05:58,  1.33it/s]

Loss: 0.0251
acc: 0.991724870938354
Epoch: 0/5............. 

 40%|████      | 321/795 [04:02<05:58,  1.32it/s]

Loss: 0.0281
acc: 0.9908256880733946
Epoch: 0/5............. 

 41%|████      | 322/795 [04:03<05:57,  1.32it/s]

Loss: 0.0298
acc: 0.990067540723083
Epoch: 0/5............. 

 41%|████      | 323/795 [04:04<05:59,  1.31it/s]

Loss: 0.0271
acc: 0.9916740674955595
Epoch: 0/5............. 

 41%|████      | 324/795 [04:04<05:57,  1.32it/s]

Loss: 0.0297
acc: 0.9900700358399369
Epoch: 0/5............. 

 41%|████      | 325/795 [04:05<05:56,  1.32it/s]

Loss: 0.0284
acc: 0.9905787853764733
Epoch: 0/5............. 

 41%|████      | 326/795 [04:06<05:55,  1.32it/s]

Loss: 0.0348
acc: 0.9880904989384289
Epoch: 0/5............. 

 41%|████      | 327/795 [04:07<05:53,  1.32it/s]

Loss: 0.0292
acc: 0.990868715580032
Epoch: 0/5............. 

 41%|████▏     | 328/795 [04:07<05:52,  1.32it/s]

Loss: 0.0245
acc: 0.9922295277943813
Epoch: 0/5............. 

 41%|████▏     | 329/795 [04:08<05:53,  1.32it/s]

Loss: 0.0347
acc: 0.9886037987337554
Epoch: 0/5............. 

 42%|████▏     | 330/795 [04:09<05:52,  1.32it/s]

Loss: 0.0299
acc: 0.990286960670711
Epoch: 0/5............. 

 42%|████▏     | 331/795 [04:10<05:52,  1.31it/s]

Loss: 0.0391
acc: 0.9875786065624805
Epoch: 0/5............. 

 42%|████▏     | 332/795 [04:10<05:50,  1.32it/s]

Loss: 0.0315
acc: 0.9892221910724854
Epoch: 0/5............. 

 42%|████▏     | 333/795 [04:11<05:50,  1.32it/s]

Loss: 0.0313
acc: 0.9903750642233259
Epoch: 0/5............. 

 42%|████▏     | 334/795 [04:12<05:49,  1.32it/s]

Loss: 0.0306
acc: 0.9904877040053447
Epoch: 0/5............. 

 42%|████▏     | 335/795 [04:13<05:48,  1.32it/s]

Loss: 0.0256
acc: 0.9905709992486852
Epoch: 0/5............. 

 42%|████▏     | 336/795 [04:13<05:48,  1.32it/s]

Loss: 0.0291
acc: 0.9902901868123754
Epoch: 0/5............. 

 42%|████▏     | 337/795 [04:14<05:47,  1.32it/s]

Loss: 0.0305
acc: 0.9908727310019485
Epoch: 0/5............. 

 43%|████▎     | 338/795 [04:15<05:47,  1.31it/s]

Loss: 0.0281
acc: 0.9907372072853425
Epoch: 0/5............. 

 43%|████▎     | 339/795 [04:16<05:45,  1.32it/s]

Loss: 0.0257
acc: 0.9916423357664234
Epoch: 0/5............. 

 43%|████▎     | 340/795 [04:16<05:44,  1.32it/s]

Loss: 0.0288
acc: 0.9905998804225071
Epoch: 0/5............. 

 43%|████▎     | 341/795 [04:17<05:44,  1.32it/s]

Loss: 0.0315
acc: 0.9890512272051626
Epoch: 0/5............. 

 43%|████▎     | 342/795 [04:18<05:43,  1.32it/s]

Loss: 0.0304
acc: 0.9901477832512315
Epoch: 0/5............. 

 43%|████▎     | 343/795 [04:19<05:42,  1.32it/s]

Loss: 0.0326
acc: 0.9893173293323331
Epoch: 0/5............. 

 43%|████▎     | 344/795 [04:19<05:41,  1.32it/s]

Loss: 0.0357
acc: 0.9876640045636053
Epoch: 0/5............. 

 43%|████▎     | 345/795 [04:20<05:42,  1.32it/s]

Loss: 0.0276
acc: 0.9916586326864233
Epoch: 0/5............. 

 44%|████▎     | 346/795 [04:21<05:39,  1.32it/s]

Loss: 0.0262
acc: 0.9907023676528884
Epoch: 0/5............. 

 44%|████▎     | 347/795 [04:22<05:37,  1.33it/s]

Loss: 0.0285
acc: 0.9905601697705901
Epoch: 0/5............. 

 44%|████▍     | 348/795 [04:22<05:37,  1.33it/s]

Loss: 0.0325
acc: 0.9894283107321524
Epoch: 0/5............. 

 44%|████▍     | 349/795 [04:23<05:37,  1.32it/s]

Loss: 0.0235
acc: 0.9923855963990997
Epoch: 0/5............. 

 44%|████▍     | 350/795 [04:24<05:36,  1.32it/s]

Loss: 0.0283
acc: 0.9908923218814849
Epoch: 0/5............. 

 44%|████▍     | 351/795 [04:25<05:37,  1.32it/s]

Loss: 0.0254
acc: 0.991735236292143
Epoch: 0/5............. 

 44%|████▍     | 352/795 [04:25<05:36,  1.32it/s]

Loss: 0.0282
acc: 0.9907541889546211
Epoch: 0/5............. 

 44%|████▍     | 353/795 [04:26<05:35,  1.32it/s]

Loss: 0.0261
acc: 0.9915125697873302
Epoch: 0/5............. 

 45%|████▍     | 354/795 [04:27<05:33,  1.32it/s]

Loss: 0.0309
acc: 0.9884705514763318
Epoch: 0/5............. 

 45%|████▍     | 355/795 [04:28<05:32,  1.32it/s]

Loss: 0.0265
acc: 0.9918147334797365
Epoch: 0/5............. 

 45%|████▍     | 356/795 [04:29<05:32,  1.32it/s]

Loss: 0.0282
acc: 0.9908284928156527
Epoch: 0/5............. 

 45%|████▍     | 357/795 [04:29<05:31,  1.32it/s]

Loss: 0.0284
acc: 0.990571596935769
Epoch: 0/5............. 

 45%|████▌     | 358/795 [04:30<05:31,  1.32it/s]

Loss: 0.0277
acc: 0.9897101588214616
Epoch: 0/5............. 

 45%|████▌     | 359/795 [04:31<05:30,  1.32it/s]

Loss: 0.0271
acc: 0.9917155806523515
Epoch: 0/5............. 

 45%|████▌     | 360/795 [04:32<05:30,  1.31it/s]

Loss: 0.0311
acc: 0.9909824549939557
Epoch: 0/5............. 

 45%|████▌     | 361/795 [04:32<05:29,  1.32it/s]

Loss: 0.0283
acc: 0.9913268256181762
Epoch: 0/5............. 

 46%|████▌     | 362/795 [04:33<05:28,  1.32it/s]

Loss: 0.0242
acc: 0.9920958981082599
Epoch: 0/5............. 

 46%|████▌     | 363/795 [04:34<05:26,  1.32it/s]

Loss: 0.0256
acc: 0.9917743403093722
Epoch: 0/5............. 

 46%|████▌     | 364/795 [04:35<05:26,  1.32it/s]

Loss: 0.0298
acc: 0.9898179280593795
Epoch: 0/5............. 

 46%|████▌     | 365/795 [04:35<05:25,  1.32it/s]

Loss: 0.0334
acc: 0.9889003522003629
Epoch: 0/5............. 

 46%|████▌     | 366/795 [04:36<05:23,  1.32it/s]

Loss: 0.0303
acc: 0.9895833333333334
Epoch: 0/5............. 

 46%|████▌     | 367/795 [04:37<05:23,  1.32it/s]

Loss: 0.0256
acc: 0.9912388675693288
Epoch: 0/5............. 

 46%|████▋     | 368/795 [04:38<05:23,  1.32it/s]

Loss: 0.0283
acc: 0.9905877770925968
Epoch: 0/5............. 

 46%|████▋     | 369/795 [04:38<05:23,  1.32it/s]

Loss: 0.0298
acc: 0.990360696517413
Epoch: 0/5............. 

 47%|████▋     | 370/795 [04:39<05:20,  1.33it/s]

Loss: 0.0225
acc: 0.992281612926495
Epoch: 0/5............. 

 47%|████▋     | 371/795 [04:40<05:20,  1.32it/s]

Loss: 0.0211
acc: 0.9929520888109845
Epoch: 0/5............. 

 47%|████▋     | 372/795 [04:41<05:19,  1.32it/s]

Loss: 0.0315
acc: 0.9893976328232841
Epoch: 0/5............. 

 47%|████▋     | 373/795 [04:41<05:19,  1.32it/s]

Loss: 0.0281
acc: 0.9907016060862215
Epoch: 0/5............. 

 47%|████▋     | 374/795 [04:42<05:17,  1.32it/s]

Loss: 0.0398
acc: 0.988406292749658
Epoch: 0/5............. 

 47%|████▋     | 375/795 [04:43<05:16,  1.33it/s]

Loss: 0.0293
acc: 0.989993136086124
Epoch: 0/5............. 

 47%|████▋     | 376/795 [04:44<05:16,  1.32it/s]

Loss: 0.0282
acc: 0.9911050191023361
Epoch: 0/5............. 

 47%|████▋     | 377/795 [04:44<05:16,  1.32it/s]

Loss: 0.0290
acc: 0.9906674781903023
Epoch: 0/5............. 

 48%|████▊     | 378/795 [04:45<05:16,  1.32it/s]

Loss: 0.0278
acc: 0.9909842479501922
Epoch: 0/5............. 

 48%|████▊     | 379/795 [04:46<05:15,  1.32it/s]

Loss: 0.0270
acc: 0.9912011173184357
Epoch: 0/5............. 

 48%|████▊     | 380/795 [04:47<05:15,  1.32it/s]

Loss: 0.0260
acc: 0.9905731647232715
Epoch: 0/5............. 

 48%|████▊     | 381/795 [04:47<05:14,  1.32it/s]

Loss: 0.0299
acc: 0.9905850706119704
Epoch: 0/5............. 

 48%|████▊     | 382/795 [04:48<05:13,  1.32it/s]

Loss: 0.0263
acc: 0.991588822839581
Epoch: 0/5............. 

 48%|████▊     | 383/795 [04:49<05:13,  1.32it/s]

Loss: 0.0299
acc: 0.9903902344003637
Epoch: 0/5............. 

 48%|████▊     | 384/795 [04:50<05:11,  1.32it/s]

Loss: 0.0346
acc: 0.9889638745533942
Epoch: 0/5............. 

 48%|████▊     | 385/795 [04:50<05:09,  1.32it/s]

Loss: 0.0269
acc: 0.9902783579538982
Epoch: 0/5............. 

 49%|████▊     | 386/795 [04:51<05:09,  1.32it/s]

Loss: 0.0270
acc: 0.9914785303231518
Epoch: 0/5............. 

 49%|████▊     | 387/795 [04:52<05:09,  1.32it/s]

Loss: 0.0302
acc: 0.9894016862492805
Epoch: 0/5............. 

 49%|████▉     | 388/795 [04:53<05:08,  1.32it/s]

Loss: 0.0325
acc: 0.990194562157815
Epoch: 0/5............. 

 49%|████▉     | 389/795 [04:54<05:08,  1.32it/s]

Loss: 0.0216
acc: 0.9934034219748505
Epoch: 0/5............. 

 49%|████▉     | 390/795 [04:54<05:08,  1.31it/s]

Loss: 0.0253
acc: 0.9914771758769986
Epoch: 0/5............. 

 49%|████▉     | 391/795 [04:55<05:06,  1.32it/s]

Loss: 0.0229
acc: 0.9928377121999931
Epoch: 0/5............. 

 49%|████▉     | 392/795 [04:56<05:05,  1.32it/s]

Loss: 0.0268
acc: 0.9922155886136491
Epoch: 0/5............. 

 49%|████▉     | 393/795 [04:57<05:04,  1.32it/s]

Loss: 0.0263
acc: 0.9915085817524842
Epoch: 0/5............. 

 50%|████▉     | 394/795 [04:57<05:03,  1.32it/s]

Loss: 0.0232
acc: 0.9925221189797505
Epoch: 0/5............. 

 50%|████▉     | 395/795 [04:58<05:03,  1.32it/s]

Loss: 0.0277
acc: 0.9919089934649563
Epoch: 0/5............. 

 50%|████▉     | 396/795 [04:59<05:01,  1.32it/s]

Loss: 0.0253
acc: 0.9927403414195867
Epoch: 0/5............. 

 50%|████▉     | 397/795 [05:00<05:01,  1.32it/s]

Loss: 0.0277
acc: 0.991824894514768
Epoch: 0/5............. 

 50%|█████     | 398/795 [05:00<05:01,  1.32it/s]

Loss: 0.0264
acc: 0.9912919730288348
Epoch: 0/5............. 

 50%|█████     | 399/795 [05:01<05:00,  1.32it/s]

Loss: 0.0251
acc: 0.9920386860883411
Epoch: 0/5............. 

 50%|█████     | 400/795 [05:02<04:59,  1.32it/s]

Loss: 0.0300
acc: 0.9904232001348845
Epoch: 0/5............. 

 50%|█████     | 401/795 [05:03<04:59,  1.31it/s]

Loss: 0.0265
acc: 0.9916682939530039
Epoch: 0/5............. 

 50%|█████     | 401/795 [05:03<04:58,  1.32it/s]


KeyboardInterrupt: ignored

In [ ]:
# torch.save(model.state_dict(), '/content/drive/MyDrive/Kaggle/model(1)/model.pth')

In [15]:
from utils import get_params
from Globals import vocab_map,classes
from tashkeel_data_set_test import TashkeelDatasetTest


v_sentences, _, v_size = get_params(vocab_map, classes, f'/content/drive/MyDrive/Kaggle/model(1)/X.pickle', '',test=True)
max_length=300
val_dataset_test = TashkeelDatasetTest(v_sentences, vocab_map['<PAD>'],max_length)

Loaded Vocab 41 {'ت': 0, 'ه': 1, 'س': 2, 'ئ': 3, 'ي': 4, 'خ': 5, 'ب': 6, 'ش': 7, 'ح': 8, 'ى': 9, 'ن': 10, 'إ': 11, 'ل': 12, 'ؤ': 13, 'ط': 14, 'ج': 15, 'ف': 16, 'آ': 17, 'ص': 18, 'م': 19, 'ا': 20, 'ع': 21, 'و': 22, 'غ': 23, 'ك': 24, 'ظ': 25, 'د': 26, 'ر': 27, 'ق': 28, 'أ': 29, 'ذ': 30, 'ة': 31, 'ء': 32, 'ز': 33, 'ض': 34, 'ث': 35, '<s>': 36, '</s>': 37, ' ': 38, '<PAD>': 39, '<UNK>': 40}
{'ت': 0, 'ه': 1, 'س': 2, 'ئ': 3, 'ي': 4, 'خ': 5, 'ب': 6, 'ش': 7, 'ح': 8, 'ى': 9, 'ن': 10, 'إ': 11, 'ل': 12, 'ؤ': 13, 'ط': 14, 'ج': 15, 'ف': 16, 'آ': 17, 'ص': 18, 'م': 19, 'ا': 20, 'ع': 21, 'و': 22, 'غ': 23, 'ك': 24, 'ظ': 25, 'د': 26, 'ر': 27, 'ق': 28, 'أ': 29, 'ذ': 30, 'ة': 31, 'ء': 32, 'ز': 33, 'ض': 34, 'ث': 35, '<s>': 36, '</s>': 37, ' ': 38, '<PAD>': 39, '<UNK>': 40}
{'َ': 0, 'ً': 1, 'ُ': 2, 'ٌ': 3, 'ِ': 4, 'ٍ': 5, 'ْ': 6, 'ّ': 7, 'َّ': 8, 'ًّ': 9, 'ُّ': 10, 'ٌّ': 11, 'ِّ': 12, 'ٍّ': 13, '': 14, 'P': 15}
Padding ..... with  300 : 9136
Done Padding ..... 9336


In [16]:
from tashkeel_result import result
result(model, val_dataset_test, batch_size=512)

  0%|          | 0/19 [00:00<?, ?it/s]

tensor([0, 6, 0,  ..., 0, 0, 5], device='cuda:0')


  5%|▌         | 1/19 [00:01<00:22,  1.27s/it]

tensor([ 0,  4,  6,  ...,  6, 14, 14], device='cuda:0')


 11%|█         | 2/19 [00:02<00:18,  1.10s/it]

tensor([ 0,  0,  6,  ...,  4, 14,  4], device='cuda:0')


 16%|█▌        | 3/19 [00:04<00:23,  1.45s/it]

tensor([ 4,  0,  8,  ...,  0, 14,  4], device='cuda:0')


 21%|██        | 4/19 [00:04<00:18,  1.21s/it]

tensor([14, 14,  8,  ..., 14,  4,  4], device='cuda:0')


 26%|██▋       | 5/19 [00:05<00:15,  1.07s/it]

tensor([2, 8, 0,  ..., 6, 4, 4], device='cuda:0')


 32%|███▏      | 6/19 [00:06<00:12,  1.02it/s]

tensor([4, 0, 8,  ..., 0, 8, 0], device='cuda:0')


 37%|███▋      | 7/19 [00:07<00:11,  1.08it/s]

tensor([ 4,  8,  0,  ...,  0, 14,  4], device='cuda:0')


 42%|████▏     | 8/19 [00:08<00:09,  1.13it/s]

tensor([ 0, 14,  6,  ...,  0,  0,  5], device='cuda:0')


 47%|████▋     | 9/19 [00:08<00:08,  1.17it/s]

tensor([ 0,  8, 14,  ...,  0,  0, 12], device='cuda:0')


 53%|█████▎    | 10/19 [00:09<00:07,  1.17it/s]

tensor([ 0,  0, 14,  ...,  0,  4,  4], device='cuda:0')


 58%|█████▊    | 11/19 [00:10<00:06,  1.18it/s]

tensor([ 0, 14,  6,  ...,  6,  4,  4], device='cuda:0')


 63%|██████▎   | 12/19 [00:11<00:05,  1.18it/s]

tensor([ 0,  0,  6,  ...,  6,  0, 14], device='cuda:0')


 68%|██████▊   | 13/19 [00:12<00:05,  1.14it/s]

tensor([ 0,  0,  0,  ...,  0, 14,  0], device='cuda:0')


 74%|███████▎  | 14/19 [00:13<00:04,  1.05it/s]

tensor([0, 0, 6,  ..., 6, 2, 2], device='cuda:0')


 79%|███████▉  | 15/19 [00:14<00:03,  1.00it/s]

tensor([0, 6, 4,  ..., 6, 4, 4], device='cuda:0')


 84%|████████▍ | 16/19 [00:15<00:03,  1.01s/it]

tensor([ 0,  0, 14,  ...,  2, 14,  2], device='cuda:0')


 89%|████████▉ | 17/19 [00:16<00:02,  1.00s/it]

tensor([0, 6, 0,  ..., 6, 4, 4], device='cuda:0')


100%|██████████| 19/19 [00:17<00:00,  1.07it/s]

tensor([0, 0, 6,  ..., 0, 8, 2], device='cuda:0')


            ID  label
0            0      0
1            1      6
2            2      0
3            3      4
4            4      6
...        ...    ...
417354  417354     14
417355  417355      6
417356  417356      0
417357  417357      8
417358  417358      2

[417359 rows x 2 columns]


In [17]:
from google.colab import files

# Download the file
files.download('csv_dictionary.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
# # Predict
# from tashkeel_evaluate import evaluate
# evaluate(model, val_dataset)
# # evaluate(model, test_dataset)


100%|██████████| 4804/4804 [00:30<00:00, 158.22it/s]


Test Accuracy: 0.9598977912557379


In [ ]:
# Dowmload
import shutil

# Specify the folder name
folder_name = "code"

# Compress the folder into a zip file
shutil.make_archive(folder_name, 'zip', folder_name)


from google.colab import files

# Download the zip file
files.download(f'{folder_name}.zip')

# Download Notebook
# Save the current notebook
# files.download("TasheelNoteBook.ipynb")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>